services:
  - type: web
    name: zfc
    runtime: node
    buildCommand: rm -rf .next && npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --dns-result-order=ipv4first
